[theme]
background = "default"
primary = "#cad3f5"
secondary = "#313244"
title = "#CBA6F7"
playing = "#91d7e3"
playing_selected = "#91d7e3"
playing_bg = "default"
highlight = "#a6da95"
highlight_bg = "default"
error = "#F5E0DC"
error_bg = "#F38BA8"
statusbar = "#8aadf4"
statusbar_progress = "#313244"
statusbar_bg = "#494d64"
cmdline = "#74C7EC"
cmdline_bg = "#181825"

[keybindings]
"Shift+d" = "noop"
