require('config.globals')
require('config.options')
require('config.keymap')
require('config.autocmd')
require('config.lsp')
require('plugins.treesitter')
require('plugins.snacks')
require('plugins.dashboard')
require('plugins.lualine')
require('plugins.gitsigns') -- you are going soon...
require('plugins.typst')
require('plugins.gruber-darker')
require('plugins.oil')
require('plugins.neotree')
